### ISSUE TITLE
rename function `dim` -> `dims`

### ISSUE THREAD

**Issue by nickrobinson251** [invenia/NamedDims.jl#10]
I know this is a bike-shed-y naming issue, but...

I think `dims` would be really nice, to go with `ndims`, `permutedims`, `dropdims`, etc.

We might have to do something ugly in the source code, like write `NamedDims.dims` all over or define an alias like `const _dims = dims`, but it might be worth doing if it's a nicer API for the user.

**Comment by oxinabox** [comment]
The main use of the `dim` function is `dim(A, :x)==1` though.

**Comment by nickrobinson251** [comment]
it's a fair point - lets leave this open to see if anyone else has an opinion, and otherwise keep as is?

**Comment by oxinabox** [comment]
when  #21 is merged this can likely be closed as the version of the function that returns `NamedTuple`s  of the function will be gone.

Though the version that accepts tuples `dim((:a, :b)) = (1,2)`
will remain,
so maybe there is still an argument to have this called `dims`?

**Comment by nickrobinson251** [comment]
I'm happy enough for this to stay as `dim` :)
