### ISSUE TITLE
unary LinearAlgebra operations

### ISSUE THREAD

**Issue by nickrobinson251** [invenia/NamedDims.jl#12]
Can we just delegate them all to `parent`?

**Comment by oxinabox** [comment]
List of unitary operations from line algebra:

- [ ] det (would be solved by having `lu!`)
- [x] tr
 -[ ] svd
- [ ] lu (would be solved by having `lu!`)
- [ ] cholesky
- [ ] pinv (would be solved by having `svd`)
- [ ] inv (would be solved by having `factorize`)
 - [ ] factorize 
 - [ ] lq
 - [ ] `logdet` (would be solved by having `lu!`)


Seems like adding the binary operator `lu!` would be most useful.

**Comment by oxinabox** [comment]
doing `lu!` requires doing `tril!` first.
