### ISSUE TITLE
More duck typing with `hasnames`?

### ISSUE THREAD

**Issue by rofinn** [invenia/NamedDims.jl#136]
AxisKeys currently defines `hasnames` for handling different types that can support named dims operations. It'd be nice if we could move that API into NamedDims.jl where I think it belongs.

https://github.com/mcabbott/AxisKeys.jl/blob/master/src/names.jl#L19

Might also help to provide a more general `NamedDims.dim` function that'll do this for you?

```
NamedDims.dim(A, d) = hasnames(A) ? NamedDims.dim(dimnames(A), d) : d
```

**Comment by mcabbott** [comment]
Just having `NamedDims.dim(::AbstractArray, d) = d` would remove almost all the uses of this. That's already what `NamedDims.dim(dimnames(A), d)` actually does. 

The otiginal point of a `hasnames` trait was to work through arbitrarily stacked wrappers, there's a bit here: https://github.com/mcabbott/NamedPlus.jl/blob/master/src/recursion.jl#L30
But (say) `cat(A,B,dims=:z)` has to dispatch on `A` or `B`, not `dims`, so I'm not sure the ability to detect and dig out deeply buried names is worth much. (I guess there's an internal `_cat(dims, A)` you could dispatch on, piratically, but there isn't always.)
