### ISSUE TITLE
Weird interaction with CircularArrays.jl

### ISSUE THREAD

**Issue by bilelomrani1** [invenia/NamedDims.jl#147]
I don't know if this is the right place to ask but I wanted to understand what is the Julian way of cumulating multiple interfaces for array types, so I experimented a little bit:
```julia
using NamedDims
using CircularArrays

a = rand(2,2)
b = NamedDimsArray{(:x, :y)}(a)
c = CircularArray(b)
```
When I call `c[x=1]` I get the following traces
```julia
ERROR: MethodError: no method matching getindex(::CircularArray{Float64,2,NamedDimsArray{(:x, :y),Float64,2,Array{Float64,2}}}; x=1)
Closest candidates are:
  getindex(::CircularArray, ::Int64) at /Users/bilelomrani/.julia/packages/CircularArrays/g4SMt/src/CircularArrays.jl:36 got unsupported keyword argument "x"
  getindex(::CircularArray, ::Int64...) at /Users/bilelomrani/.julia/packages/CircularArrays/g4SMt/src/CircularArrays.jl:38 got unsupported keyword argument "x"
  getindex(::AbstractArray, ::Any...) at abstractarray.jl:1057 got unsupported keyword argument "x"
Stacktrace:
 [1] top-level scope at REPL[39]:1
```

But, when I revert the order of composition like so

```julia
a = rand(2,2)
b = CircularArray(a)
c = NamedDimsArray{(:x, :y)}(b)
```
I get the desired output
```julia
julia> c
2×2 NamedDimsArray{(:x, :y),Float64,2,CircularArray{Float64,2,Array{Float64,2}}}:
 0.10984   0.834483
 0.963641  0.348574

julia> c[x=1]
2-element NamedDimsArray{(:y,),Float64,1,CircularArray{Float64,1,Array{Float64,1}}}:
 0.10984001542804256
 0.8344826360244295

julia> c[x=3]
2-element NamedDimsArray{(:y,),Float64,1,CircularArray{Float64,1,Array{Float64,1}}}:
 0.10984001542804256
 0.8344826360244295
```

I don't know if this is an expected behavior, I expected the indexing to not depend on the order of composition. I didn't experiment further yet, but my plan is to try to compose many wrapper types (`CircularArray`, `NamedDims`, `CuArray`, etc.) to see how these interfaces compose with each other. Ideally this should work right?

**Comment by mzgubic** [comment]
Hi Bilel, thanks or the question!

The reason the second example works the way you expect is because `NamedDims` implements the `getindex` method _with keywords_ here: https://github.com/invenia/NamedDims.jl/blob/1ef0b73ec26ff870575bd33a530e29b1c18b0d01/src/wrapper_array.jl#L139-L165

The error you are seeing happens because the `CircularArray` does not implement a `getindex` method with keywords. The solution would be to implement such a method, which then calls the same method on the parent array. I am not familiar with the package so not sure how willing the developers would be to implement this, or even to review your PR.

**Comment by mcabbott** [comment]
It's a pity that wrappers don't compose very well, and this is one result of that. 

To expand a little, the keywords don't participate in dispatch, and so when Julia finds that the method it chose (based on `typeof(c)` alone) doesn't accept them, it gives up. As noted, CircularArrays could explicitly support this, but then that package would need to depend on NamedDims.

While this package does not condone piracy, it might not in fact be too dangerous to invent some catch-all method which could check for names inside. Here's the 1-minute attempt:
```julia
Base.parent(x::CircularArray) = x.data # they should define this anyway

Base.getindex(x::Any; kw...) = begin # piratical fall-back method
    @info "getindex(::Any)" typeof(x) typeof(parent(x))
    parent(x)===x ? error() : getindex(parent(x); kw...)
end

c[x=1]
c[x=3] # fails to apply circular-ness
```
A more serious version would, after figuring out (its best guess at) what dimensions they keywords indicate, call the original `getindex` with those.

**Comment by bilelomrani1** [comment]
I understand better, thank you @mzgubic and @mcabbott. Maybe it was a bit too greedy to expect this level of interoperability out of the box but I imagined that if there were one language allowing this, it would have been Julia.

**Comment by oxinabox** [comment]
The right thing to do is to put the NamedDimsArray on the outside.
As you found at the start.
NamedDimsArrays like to be on the outside, because as found, most wrapper arrays do not pass on kwargs of getindex, before delegating them.

**Comment by bilelomrani1** [comment]
Makes sense to me now, the independence on the wrappers' order seems hard to get, with too few benefits.

**Comment by oxinabox** [comment]
The dream would be for it to do so.
It might be worth a PR to circular arrays to make it pass on kwargs.

**Comment by mcabbott** [comment]
But is passing on keywords enough here? If it gets an index `k=10`, it has to look up `dim(parent(A), :k)` to know which `d` to use in `mod(10, axes(A,d))`.

**Comment by bilelomrani1** [comment]
I mean, there is nothing really specific about `CircularArrays.jl` here, we'll have similar problems with `OffsetArrays.jl` and probably other libraries out there... Perhaps Julia is missing a layer of abstraction when it comes to indexing arrays but I cannot get my head around it just yet

**Comment by oxinabox** [comment]
> But is passing on keywords enough here? If it gets an index `k=10`, it has to look up `dim(parent(A), :k)` to know which `d` to use in `mod(10, axes(A,d))`.  

Ah true.

**Comment by Tokazama** [comment]
If accessing the dimension names doesn't depend on directly interacting with `NamedDimsArray` then kwargs wouldn't need to be propagated. Perhaps incorporating it into something like ArrayInterface.jl like the following would work

```julia
has_dimnames(x) = has_dimnames(typeof(x))
function has_dimnames(::Type{T}) where {T}
    if parent_type(T) <: T
        return false
    else
        return has_dimnames(parent_type(T))
    end
end

function ArrayInterface.getindex(x; named_inds...)
    if has_dimnames(x)
        return x[order_named_inds(Val(dimnames(x)), named_inds.data)...]
    else
        error("Type $(typeof(x)) does not have named dimensions")
    end
end
```

And then in this package you could define:
```julia
has_dimnames(::Type{T}) where {T<:NamedDimsArray} = true
```

**Comment by oxinabox** [comment]
Could do maybe.
Right now ArrayInterface is a package with a huge number of dependencies.
Possibly because it is (for now) backwards and it depends on things rather than things depending on it.
I would not want to add it as a dependencies of NamedDims or it would drag in all that cuda stuff

**Comment by Tokazama** [comment]
The only dependency that's not in the standard library is Requires.jl. Everything else is extra.

**Comment by mcabbott** [comment]
If `ArrayInterface.getindex` is called by `A[μ=1]`, then this seems to have the same piracy problem as my sketch above. 

But there also has to be a mechanism to pass these names outwards through wrappers, which may alter the dimensions. For example, I have a package which generalises PermutedDimsArray to allow generalised Diagonal & some reshapes:
```julia
julia> transmute(b, (2,2,1)) # needs names (:y, :x, :x) 
2×2×2 transmute(::NamedDimsArray{(:x, :y),Float64,2,Array{Float64,2}}, (2, 2, 1)) with eltype Float64:
[:, :, 1] =
 0.853238   ⋅ 
  ⋅        0.721669

[:, :, 2] =
 0.558938   ⋅ 
  ⋅        0.381018

julia> transmute(b, (1,0,2)) # needs names (:x, :_, :y) 
2×1×2 transmute(::NamedDimsArray{(:x, :y),Float64,2,Array{Float64,2}}, (1, 0, 2)) with eltype Float64:
...
```
So I guess you need some kind of `outmap(::MyArray, inner_names) -> outer_names` which packages overload, too. Which is what some iteration of NamedPlus had...

**Comment by Tokazama** [comment]
> If ArrayInterface.getindex is called by `A[μ=1]`, then this seems to have the same piracy problem as my sketch above?

What I'm suggesting/considering here is that `ArrayInterface.getindex` consider key word arguments as dimension names by default and that any array type that might wrap a parent array can take advantage of this by defining`Base.getindex(x::NewType; named_inds...) = ArrayInterface.getindex(x; named_inds...)` and a `parent_type` method. The downside to this is that if some new type `T` accepts key word arguments for some purpose other than named dimensions then the key word argument would not be propagated forward to `getindex` if `T` is wrapped as a parent. For example...

```julia
function ArrayInterface.getindex(x::NewType; add_one=false, kwargs...)
    if add_one
        return x[order_named_inds(Val(dimnames(x)), kwargs.data)...] .+ 1
    else
        return x[order_named_inds(Val(dimnames(x)), kwargs.data)...]
    end
end

x  # instance of `NewType` wrapping array with dimnames (:x, :y)
y  # wrapper array that happens to have a parent type `NewType`

x[add_one=true, x = 1]  # would add one to `parent(x)[1, :]`
y[add_one=true, x = 1]  # would error because kwargs aren't propagated forward and assumes they are dimension names
```

Currently, there's no guarantee that using keyword arguments will end up propagating forward to the parent data anyway, so it's not a huge loss.

> So I guess you need some kind of outmap(::MyArray, inner_names) -> outer_names which packages overload, too. Which is what some iteration of NamedPlus had...

Absolutely! As you can see [here](https://github.com/SciML/ArrayInterface.jl/blob/889b6c59eca7c5c9db89747d525c0858ed109530/src/stridelayout.jl#L27), there are already other cases where ArrayInterface takes information from a parent type and is altered based on the wrapper. If we took this route we'd also want to define something like

```julia
@generated function dimnames(::Type{T}) where {N,A,I,T<:SubArray{<:Any,N,A,I}}
    e = Expr(:tuple)
    d = dimnames(A)
    for i in 1:N
        if argdims(A, I.parameters[i]) > 0
            push!(e.args, d[i])
        end
    end
    return e
end
```

**Comment by Tokazama** [comment]
I created a PR to ArrayInterface.jl that uses `dimnames` for kwargs. I don't want to step on any toes, so if it is inappropriate for me to use some of the work related to `dimnames` feel free to comment on the PR and let me know.
