### ISSUE TITLE
Passing a DataFrame as an argument to a model

### ISSUE THREAD

**Issue by fredcallaway** [invenia/NamedDims.jl#166]
I was surprised to find that passing a DataFrame as an argument to a model doesn't work.

Example: infer the means of a Normal mixture with observed latent assignments

```julia
using DataFrames, Turing

# generate data
data = mapreduce(vcat, 1:3) do z
    μ = rand(Normal(0, 1))
    map(1:2) do i
        x = rand(Normal(μ, 1))
        (;z, x)
    end
end |> DataFrame
# 6×2 DataFrame
#  Row │ z      x         
#      │ Int64  Float64   
# ─────┼──────────────────
#    1 │     1   1.27114
#    2 │     1   3.39653
#    3 │     2   2.03258

# model 1: pass columns separately
@model function model(z, x)
    μ ~ filldist(Normal(0, 1), maximum(z))
    for i in eachindex(x)
        x[i] ~ Normal(μ[z[i]], i)
    end
end

sample(model(data.z, data.x), NUTS(), 100) 
# Works fine!

# model 2: pass dataframe
@model function model(data)
    z = data.z; x = data.x
    μ ~ filldist(Normal(0, 1), maximum(z))
    for i in eachindex(x)
        x[i] ~ Normal(μ[z[i]], i)
    end
end

sample(model(data), NUTS(), 100)
# ERROR: TypeError: in typeassert, expected Float64, got a value of type ForwardDiff.Dual{Nothing, Float64, 9}   
```

What's going on here? I was hoping I could treat Turing model definitions as regular Julia code but I guess there's some magic going on under the hood that makes that a bad strategy. I read through all the tutorials and didn't see any indication that this wouldn't work. It might be nice to have some kind of warning that this won't work (either in the docs or in the code).

**Comment by oxinabox** [comment]
I think you openned this on the wrong repo friend.
Maybe too many tabs?

**Comment by fredcallaway** [comment]
😅indeed, sorry for wasting your time!
