### ISSUE TITLE
Dimensions modifying functions

### ISSUE THREAD

**Issue by oxinabox** [invenia/NamedDims.jl#2]
These are beyond the scope of #1,
as it is useful without them.

The following function would also be useful to have
But need more care when implementing

 - [ ] `permutedims`
 - [ ] `transpose`
 - [ ] `dropdims`
 - [ ] `reshape`
 - [ ] `vec`

**Comment by oxinabox** [comment]
#7 adds:
`dropdims`, `permutedims`,  and `transpose` 
Mostly as a side effect of what it is actually about.

Though it only adds the 1 arg form of `permutedims` which only works on `Matrixes` and `Vectors`

**Comment by Tokazama** [comment]
It would be nice if there was something similar to `AxisArrays.permutation` that accepts names instead of permutations.

**Comment by oxinabox** [comment]
I have made a superate issue for that, since it is not one that modifies the dimensions.
More of a utility function.

**Comment by iamed2** [comment]
The 2-arg `permutedims` could be implemented in the same way.

I wonder if `PermutedDimsArray` should be modified to make a NamedDimsArray wrapping a `PermutedDimsArray`?

**Comment by oxinabox** [comment]
this is out of date and needs updating I think this is mostly done?

**Comment by oxinabox** [comment]
I am going to close this and anything along these lines that is missing, we can open a new issue for
