### ISSUE TITLE
Operations on unnamed arrays adopt names

### ISSUE THREAD

**Issue by jariji** [invenia/NamedDims.jl#215]
> If you perform an operation between another AbstractArray and a NamedDimsArray, then the result will take its names from the NamedDimsArray. You can use this to bypass the protection, e.g. `NamedDimsArray{(:time,)}(ones(5)) + parent(NamedDimsArray{(:place,)}(ones(5)))` is allowed.

I can see wanting to ignore dimension names in some cases. However, the current implementation of the idea could lead to accidents. If I add an `Array` to a `NamedDimsArray`, I'll get a `NamedDimsArray`, which could easily be the wrong kind. As an anology, Unitful.jl doesn't allow `5m + 3 == 8m` , but offers two other ways of getting this result. I  wonder if these options might be considered for a future version:

- `NamedDimsArray{dimnames(a)}(unname(a) + b)` analogous to `(ustrip(a) + b) * unit(a)`
- `a + NamedDimsArray{dimnames(a)}(b)` analogous to `a + unit(a)*b`

These don't have the potential for accidentally adopting incorrect dimensions. `a::NamedDimsArray+ b::Array` could error then.

**Comment by oxinabox** [comment]
This is an intentional feature of this package and is crucial to its original use case.
Namely to get named outputs out of Flux, if you put named inputs in, without changing the Flux code.
