### ISSUE TITLE
Used `Base.names`

### ISSUE THREAD

**Issue by oxinabox** [invenia/NamedDims.jl#22]
After some reflection, I think we should overload `Base.names`
DataFrames does it, and we have a way better argument than they do.

**Comment by timholy** [comment]
On the other hand, `struct` uses `fieldnames` and NamedTuples doesn't define either one. Ref https://github.com/JuliaImages/ImageAxes.jl/pull/33.

I'm not sure I'm against `names`, but I'm not sure I'm for it either. I know what `MyModule.funcname` does. I know what `mystruct.fldname` does. Heck, I know what `df.colname` does. What does `nda.x` do?

**Comment by oxinabox** [comment]
>  NamedTuples doesn't define either one
NamedTuple instances do define `propertynames`

```
julia> a = (a=1, b=2)
(a = 1, b = 2)

julia> propertynames(a)
(:a, :b)
```



>  What does nda.x do?

Errors. 
We definately should not use `fieldnames`, or `propertynames`
`nda[x=1, y=2]` on the other hand...

> I'm not sure I'm against names, but I'm not sure I'm for it either.

My feelings exactly.
In practice though I do want this function often,
but that might be a symptom, of another thing,
and also can always call it `dimnames` and export it.

**Comment by timholy** [comment]
I generally like `dimnames`. And yes, the *functionality* is very useful, just wondering what name it should have.

**Comment by Tokazama** [comment]
I'm coming around to `dimnames`. It has a succinct and descriptive name. This also leaves the use of `names` open for concurrent use with `dimnames` if someone in the future decides that they need to use it concurrently for an array with dimension names.

**Comment by Tokazama** [comment]
Is this a desirable feature that's just waiting for a pull request, or is it a no go?

**Comment by oxinabox** [comment]
Yeah, I think lets make `dimnames` happen.

**Comment by nickrobinson251** [comment]
Any thoughts on `dims` over `dimnames` for this function? 

I slightly prefer it. But I am also fine with `dimnames` and think most important is having this functionality in an easier-to-use way than `NamedDims.names`.

**Comment by mcabbott** [comment]
+1 for giving the internal function `NamedDims.names` a better and non-clashing name (and a dep-warning). My vote would actually be for `names_or_defaults` to be 100% clear, but `dimnames` works too.

I still think that in addition to this fix, we should also make `Base.names` work on `NamedDimsArray`s only, and make `names(A,d)` work like `size(A,d)`, `axes(A,d)` etc.

**Comment by Tokazama** [comment]
I slightly prefer `dimnames` because it's more descriptive and internally there is already `dim` which is really close to `dims`.

The problem with using `Base.names` is that it precludes any parent type from using it (e.g., something with Table traits). One could always wrap a `NamedDims` array inside of another array if you want to change the behavior of `Base.names`, but that would kind of eliminate the point of using this package then.

**Comment by timholy** [comment]
I haven't reviewed this recently, but just on general principles I'd urge caution about supplying default names if the array doesn't already have them---my vote is to return `nothing` or `missing` in such cases, and force the coder to then call `defaultnames` if s/he really wants names. See discussion in https://github.com/JuliaImages/ImageCore.jl/pull/89.

**Comment by nickrobinson251** [comment]
> internally there is already dim which is really close to dims.

Actually, that has convinced me in favour of `dims`! 😆 

I think this is nice/good:
```julia
julia> nda = NamedDimsArray(rand(2, 3), (:r, :c));

julia> dim(nda, :c)
2

julia> dims(nda)
(:r, :c)
```

**Comment by mcabbott** [comment]
Not suggesting changing it now, but `dim` already seems confusing IMO, since it returns dims:
```julia
julia> dim(nda, (:c, :r))
(2, 1)
```

**Comment by timholy** [comment]
So `dim` returns an Int but `dims` returns a tuple of symbols? Seems confusing.

**Comment by nickrobinson251** [comment]
related https://github.com/invenia/NamedDims.jl/issues/10

maybe this should be `dims` in all cases 😆 

that is
```julia
julia> nda = NamedDimsArray(rand(2, 3), (:r, :c));

julia> dims(nda)
(:r, :c)

julia> dims(nda, :c)
2

julia> dims(nda, 2)  
:c  

julia> dims(nda, (2, 1))  
(:c , :r)
```

**Comment by Tokazama** [comment]
It may make more sense for `dim` to be `finddims` so it's consistent with the other `find*` functions in base.

**Comment by mcabbott** [comment]
But every second function contains something like `numerical_dims = dim(A, dims)`, which needs to always return the integer(s). You need a function which does this. It could be called `finddims` or `numerical_dims` but doubt the churn is worth it.

**Comment by oxinabox** [comment]
There is a tiering system of things that are hard in software engineering.

- **Easy**: hello world
- **Moderate**: Travelling Salesman
- **Hard**: Naming things
- **Impossible**: Video Conferencing software

**Comment by Tokazama** [comment]
TBH I don't feel strongly at all about renaming `dim`. My comment was mostly an attempt to reduce the cognitive ambiguity between `dim` and `dims`. However, it sounds like `dims` has other shortcomings.

>I haven't reviewed this recently, but just on general principles I'd urge caution about supplying default names if the array doesn't already have them---my vote is to return nothing or missing in such cases, and force the coder to then call defaultnames if s/he really wants names. See discussion in JuliaImages/ImageCore.jl#89.

Given the potential complexity of default names in this package (how they're encoded internally, wild card names, etc.), perhaps it's best to just decide what the user facing API is (e.g., `names`, `dimnames`) and punt the specific of how default names will work in another issue. I don't think the choice here will necessarily limit implementing default names under `dimnames`, `default_names`, etc..

**Comment by mcabbott** [comment]
But #83 just renames `NamedDims.names` to `dimnames`, right? This does still return default names, as it should e.g. for `new_names = unify_names(dimnames(a), dimnames(b), dimnames.(cs)...)` to work correctly. Because `unify_names` still wants `:_` wildcards.

**Comment by oxinabox** [comment]
> Perhaps the question is whether the exported function should be this one with wildcards, or something else.

Indeed.
