### ISSUE TITLE
VectorTranspose * Vector broken

### ISSUE THREAD

**Issue by oxinabox** [invenia/NamedDims.jl#36]
```
julia> x = NamedDimsArray{(:a,)}([1,2,3])
3-element NamedDimsArray{(:a,),Int64,1,Array{Int64,1}}:
 1
 2
 3


julia> x'*x
ERROR: MethodError: no method matching NamedDimsArray{(:_,),T,N,A} where A<:AbstractArray{T,N} where N where T(::Int64)
```

Correct answer is:
`14`
Not a `Array` at all, just a scalar.

**Comment by nickrobinson251** [comment]
I presume we want to require names match? so (once fixed) this should error?
```julia
a = NamedDimsArray{(:a,)}([1,2,3])
b = NamedDimsArray{(:b,)}([1,2,3])
a' * b
```
What about for `dot`? Would we want `dot(a, b)` to error? 

Note that `dot` ignores dimensionality (and check only length), so `dot(a, a) == dot(a', a) == dot(a, a') == dot(a', a')` (which is probably the correct behaviour, but may not be https://github.com/JuliaLang/julia/issues/32395 ...and is anyway maybe surprising at first)
