### ISSUE TITLE
Cov result looks confusing

### ISSUE THREAD

**Issue by tk3369** [invenia/NamedDims.jl#41]
By taking covariance of a 2D NamedDimsArray (A & B), I would expect the result to be one that is transformed to the other dimension i.e. (B & B).  For example,

```
julia> using Statistics, NamedDims

julia> stock_returns = NamedDimsArray{(:return, :stock)}(rand(-0.1:0.0001:0.1, 30, 3));

julia> typeof(stock_returns)
NamedDimsArray{(:return, :stock),Float64,2,Array{Float64,2}}

julia> cov(stock_returns, dims = :return)
3×3 NamedDimsArray{(:return, :stock),Float64,2,Array{Float64,2}}:
 0.00334097    8.62305e-5    0.000456623
 8.62305e-5    0.00406993   -0.000750522
 0.000456623  -0.000750522   0.00397614 
```

I would expect the result to have type:
```
3×3 NamedDimsArray{(:stock, :stock),Float64,2,Array{Float64,2}}:
```

**Comment by nickrobinson251** [comment]
I suspect the same is true of `cor` -- i think neither should be here https://github.com/invenia/NamedDims.jl/blob/cfe526e07772b722cfd0703179ffe8f2a6b1608e/src/functions.jl#L25 i.e. they should not keep the original names

**Comment by oxinabox** [comment]
Correct.
Should be a fairly small PR if you are interested.

**Comment by tk3369** [comment]
@nickrobinson251  I'm a little confused by the comment 
> they should not keep the original names

Are you saying that the result should be a regular `AbstractArray` rather than `NamedDimsArray`?  I was thinking that `cov(stock_returns, dims = :return)` would give me dimensions `(:stock, :stock)`.

**Comment by nickrobinson251** [comment]
I am saying the same. :)

It shouldn't have original names (a, b) it should have matching names (a, a) or if dims=2 (b, b)
