### ISSUE TITLE
What should the behavour of map and collect be?

### ISSUE THREAD

**Issue by oxinabox** [invenia/NamedDims.jl#75]
>  it is a more contentious feature ...

If you believe `map` & `collect`ed generators ought not to simply propagate names along, then perhaps open a discussion issue?

_Originally posted by @mcabbott in https://github.com/invenia/NamedDims.jl/pull/73#issuecomment-541540604_

**Comment by mcabbott** [comment]
OK, my take is that all of these ought to propagate names:
```
A = [f(x) for x in nda]
B = map(f, nda)
C = [g(x,y) for x in nda, y in ndb]  # (names(nda)..., names(ndb)...)
D = map(g, nda, ndb)                 # unify(names(nda), names(ndb))
E = filter(h, nda)
```
Only some of them do now. What's the argument against any of these? Or what other cases need to be worried about before fixing them?

**Comment by oxinabox** [comment]
I am coming around to the the idea.
`map(f, ::Tuple)::Tuple) afterall.

And also recently @glennmoy  had code that would have benifited from this
