### ISSUE TITLE
Allocation tests post-1.3

### ISSUE THREAD

**Issue by mcabbott** [invenia/NamedDims.jl#89]
Many of the allocation tests fail on master (and on 1.4), essentially because this is nonzero:
```
julia> @allocated (() -> (1+1))()
62992

julia> VERSION
v"1.5.0-DEV.88"
```
On slack, kristofferc points me to https://github.com/JuliaLang/julia/pull/33717, after which the `@allocated` macro no longer excludes compilation cost. So we will need to adjust how we test.

**Comment by iamed2** [comment]
I just came here to make this issue, based on your own Slack conversation, because I'm daft 😆

**Comment by iamed2** [comment]
This is true:
```
julia> f = () -> (1+1)
#17 (generic function with 1 method)

julia> @allocated f()
61808

julia> @allocated f()
0
```

So I think all we'd need is a wrapper macro that would run code that returns a function, call it without arguments, then call `@allocated` on it, since AFAICT our only problematic case just defines an anonymous function and calls it without arguments.

**Comment by mcabbott** [comment]
One could also adapt `@btime` to make a `@ballocated`. 

Or perhaps just dispense with these `(() -> ...)()` things, since the functions inside should already have been called before? Does zero allocations imply that constant prop. is working correctly?

**Comment by iamed2** [comment]
Yes I believe those anonymous functions are written that way in order to test that constant prop. is working.
