### ISSUE TITLE
Add `NamedDims.dim` to README?

### ISSUE THREAD

**Issue by nickrobinson251** [invenia/NamedDims.jl#97]
users may want to know "which dimension is `:y`?"

ideally they wouldn't need to, as working with numbered dimensions would be replaced by working with named dimensions, but they might

without knowing about `dim`, they may write something like `julia> findfirst(==(:y), dimnames(nda))`.

Maybe we should "show" more functionality in general
```julia
julia> nda = NamedDimsArray{(:w, :x, :y, :z)}(ones(10, 20, 30, 40));

julia> dimnames(nda)
(:w, :x, :y, :z)

julia> NamedDims.dim(nda, :y)
3
```

**Comment by mcabbott** [comment]
If you do, worth pointing out that it understands multiple dims, and that it's exported: 
```julia
julia> dim(nda, (:y,:w))
(3, 1)
```
